# Generated by Django 3.0.8 on 2020-07-05 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200705_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='citle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 12, 8, 50, 719443), verbose_name='date published'),
        ),
    ]
