# Generated by Django 3.0.8 on 2020-07-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200705_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_sumary',
            field=models.TextField(default='Summary of article', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 10, 56, 9, 377842), verbose_name='date published'),
        ),
    ]
