# Generated by Django 3.0.8 on 2020-07-06 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200706_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='display_sumary',
            new_name='display_summary',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 10, 59, 24, 828557), verbose_name='date published'),
        ),
    ]
